version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RECIPIENT_ADDRESS=0x915082634caD7872D789005EBFaaEF98f002F9E0
      - NEXT_PUBLIC_SUPABASE_URL=your_supabase_url
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
    volumes:
      - .:/app
      - /app/node_modules 